# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-31 15:33
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20171211_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='qmatrix',
            name='amount',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='qmatrix',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
    ]
