# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-01 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_menu_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='day_open',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
