# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-03 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_informations'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, default='user', max_length=10, null=True),
        ),
    ]
