# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-04 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_profile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField(blank=True, default=1, null=True)),
                ('date_expire', models.DateField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Store')),
            ],
        ),
    ]
