# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-04 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_coupon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='getcoupon',
            name='amount',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
