# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 00:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_getcoupon_amount'),
        ('mainapp', '0019_store_delivery_boundary'),
    ]

    operations = [
    ]
