# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_auto_20180105_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
