# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_order_payment'),
        ('mainapp', '0023_merge_20180105_0629'),
    ]

    operations = [
    ]
