# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_merge_20180106_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_type', models.CharField(blank=True, max_length=10, null=True)),
                ('etc', models.CharField(blank=True, max_length=50, null=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Coupon')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Menu')),
            ],
        ),
    ]
