# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_codetype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codetype',
            old_name='etc',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='codetype',
            name='menu',
        ),
    ]
