# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-06 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storebyuser',
            name='store',
        ),
        migrations.RemoveField(
            model_name='storebyuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='StoreByUser',
        ),
    ]
