# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-06 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_storebyuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment',
            new_name='payment_method',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='created_by',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='person_type',
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(upload_to='menu/'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='', upload_to='profilePicture/'),
        ),
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.ImageField(upload_to='stores/'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='store',
            name='place',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='store',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
        migrations.AlterField(
            model_name='store',
            name='tags',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
