# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-06 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_usecoupon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UseCoupon',
            new_name='DisplayHome',
        ),
    ]
