# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-06 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_auto_20180107_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayhome',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Review'),
        ),
    ]
