# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-07 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_displayhome_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
    ]
