# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-07 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0039_auto_20180107_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytime',
            name='friday_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliverytime',
            name='monday_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliverytime',
            name='saturday_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliverytime',
            name='sunday_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliverytime',
            name='thursday_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliverytime',
            name='tuesday_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliverytime',
            name='wednesday_off',
            field=models.BooleanField(default=False),
        ),
    ]
